Repository kangraemin/RxJavaStudy, pull requests merged in 2022-04, with the labels that each got.

#30 1주차 과제 - 옵저버패턴
  Homework/Homework_1/Homework_1.xcodeproj/project.pbxproj
  Homework/Homework_1/Homework_1.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Homework/Homework_1/Homework_1.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Homework/Homework_1/Homework_1.xcodeproj/project.xcworkspace/xcuserdata/mmobidoo.xcuserdatad/UserInterfaceState.xcuserstate
  Homework/Homework_1/Homework_1.xcodeproj/xcuserdata/mmobidoo.xcuserdatad/xcschemes/xcschememanagement.plist
  Homework/Homework_1/Homework_1/AppDelegate.swift
  Homework/Homework_1/Homework_1/Assets.xcassets/AccentColor.colorset/Contents.json
  Homework/Homework_1/Homework_1/Assets.xcassets/AppIcon.appiconset/Contents.json
  Homework/Homework_1/Homework_1/Assets.xcassets/Contents.json
  Homework/Homework_1/Homework_1/Base.lproj/LaunchScreen.storyboard
  Homework/Homework_1/Homework_1/Base.lproj/Main.storyboard
  Homework/Homework_1/Homework_1/Info.plist
  Homework/Homework_1/Homework_1/SceneDelegate.swift
  Homework/Homework_1/Homework_1/Subject/Observer.swift
  Homework/Homework_1/Homework_1/Subject/Subject.swift
  Homework/Homework_1/Homework_1/View/PercentImageView.swift
  Homework/Homework_1/Homework_1/View/PercentLbl.swift
  Homework/Homework_1/Homework_1/View/PercentSliderView.swift
  Homework/Homework_1/Homework_1/View/PercentTextView.swift
  Homework/Homework_1/Homework_1/ViewController/ObserverPatternViewController.swift
Labels: need merge

#26 1주차 과제
  Homework/Taewoo/README.md
  Homework/Taewoo/RxStudy/.gitignore
  Homework/Taewoo/RxStudy/Podfile
  Homework/Taewoo/RxStudy/RxStudy.xcodeproj/project.pbxproj
  Homework/Taewoo/RxStudy/RxStudy.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Homework/Taewoo/RxStudy/RxStudy.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Homework/Taewoo/RxStudy/RxStudy.xcodeproj/project.xcworkspace/xcuserdata/taewookim.xcuserdatad/UserInterfaceState.xcuserstate
  Homework/Taewoo/RxStudy/RxStudy.xcodeproj/xcuserdata/taewookim.xcuserdatad/xcschemes/xcschememanagement.plist
  Homework/Taewoo/RxStudy/RxStudy/AppDelegate.swift
  Homework/Taewoo/RxStudy/RxStudy/Assets.xcassets/AccentColor.colorset/Contents.json
  Homework/Taewoo/RxStudy/RxStudy/Assets.xcassets/AppIcon.appiconset/Contents.json
  Homework/Taewoo/RxStudy/RxStudy/Assets.xcassets/Contents.json
  Homework/Taewoo/RxStudy/RxStudy/Base.lproj/LaunchScreen.storyboard
  Homework/Taewoo/RxStudy/RxStudy/Base.lproj/Main.storyboard
  Homework/Taewoo/RxStudy/RxStudy/Info.plist
  Homework/Taewoo/RxStudy/RxStudy/ObsProgressView.swift
  Homework/Taewoo/RxStudy/RxStudy/ObsStepper.swift
  Homework/Taewoo/RxStudy/RxStudy/ObsTF.swift
  Homework/Taewoo/RxStudy/RxStudy/ObsView.swift
  Homework/Taewoo/RxStudy/RxStudy/ObserverProtocol.swift
  Homework/Taewoo/RxStudy/RxStudy/SceneDelegate.swift
  Homework/Taewoo/RxStudy/RxStudy/Subject.swift
  Homework/Taewoo/RxStudy/RxStudy/ViewController.swift
Labels: need merge

#28 1주차 과제 observer pattern
  Homework/.DS_Store
  Homework/Handnew04/.DS_Store
  Homework/Handnew04/Homework/2주차과제.md
  Homework/Handnew04/RxStudy/.gitignore
  Homework/Handnew04/RxStudy/app/.gitignore
  Homework/Handnew04/RxStudy/app/build.gradle
  Homework/Handnew04/RxStudy/app/proguard-rules.pro
  Homework/Handnew04/RxStudy/app/src/androidTest/java/com/example/rxstudy/ExampleInstrumentedTest.kt
  Homework/Handnew04/RxStudy/app/src/main/AndroidManifest.xml
  Homework/Handnew04/RxStudy/app/src/main/java/com/example/rxstudy/MainActivity.kt
  Homework/Handnew04/RxStudy/app/src/main/java/com/example/rxstudy/observerpattern/DefaultObserver.kt
  Homework/Handnew04/RxStudy/app/src/main/java/com/example/rxstudy/observerpattern/DefaultSubject.kt
  Homework/Handnew04/RxStudy/app/src/main/java/com/example/rxstudy/observerpattern/ui/ObserverPatternActivity.kt
  Homework/Handnew04/RxStudy/app/src/main/java/com/example/rxstudy/observerpattern/ui/PercentEditText.kt
  Homework/Handnew04/RxStudy/app/src/main/java/com/example/rxstudy/observerpattern/ui/PercentSeekBar.kt
  Homework/Handnew04/RxStudy/app/src/main/java/com/example/rxstudy/observerpattern/ui/PercentTextView.kt
  Homework/Handnew04/RxStudy/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  Homework/Handnew04/RxStudy/app/src/main/res/drawable/ic_launcher_background.xml
  Homework/Handnew04/RxStudy/app/src/main/res/layout/activity_main.xml
  Homework/Handnew04/RxStudy/app/src/main/res/layout/activity_pattern_observer.xml
  Homework/Handnew04/RxStudy/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Homework/Handnew04/RxStudy/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Homework/Handnew04/RxStudy/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  Homework/Handnew04/RxStudy/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  Homework/Handnew04/RxStudy/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  Homework/Handnew04/RxStudy/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  Homework/Handnew04/RxStudy/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  Homework/Handnew04/RxStudy/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  Homework/Handnew04/RxStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  Homework/Handnew04/RxStudy/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  Homework/Handnew04/RxStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  Homework/Handnew04/RxStudy/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  Homework/Handnew04/RxStudy/app/src/main/res/values-night/themes.xml
  Homework/Handnew04/RxStudy/app/src/main/res/values/colors.xml
  Homework/Handnew04/RxStudy/app/src/main/res/values/strings.xml
  Homework/Handnew04/RxStudy/app/src/main/res/values/themes.xml
  Homework/Handnew04/RxStudy/app/src/main/res/xml/backup_rules.xml
  Homework/Handnew04/RxStudy/app/src/main/res/xml/data_extraction_rules.xml
  Homework/Handnew04/RxStudy/app/src/test/java/com/example/rxstudy/ExampleUnitTest.kt
  Homework/Handnew04/RxStudy/build.gradle
  Homework/Handnew04/RxStudy/gradle.properties
  Homework/Handnew04/RxStudy/gradle/wrapper/gradle-wrapper.jar
  Homework/Handnew04/RxStudy/gradle/wrapper/gradle-wrapper.properties
  Homework/Handnew04/RxStudy/gradlew
  Homework/Handnew04/RxStudy/gradlew.bat
  Homework/Handnew04/RxStudy/settings.gradle
Labels: need merge

#27 1주차: 옵저버 패턴
  .gitignore
  Homework/Sunwoong/Homework/2주차 homework/homework
  Homework/Sunwoong/Homework/ObserverPatternInSwift/.gitignore
  Homework/Sunwoong/Homework/ObserverPatternInSwift/ObserverPatternInSwift.xcodeproj/project.pbxproj
  Homework/Sunwoong/Homework/ObserverPatternInSwift/ObserverPatternInSwift.xcodeproj/xcshareddata/xcschemes/ObserverPatternInSwift.xcscheme
  Homework/Sunwoong/Homework/ObserverPatternInSwift/ObserverPatternInSwift/AppDelegate.swift
  Homework/Sunwoong/Homework/ObserverPatternInSwift/ObserverPatternInSwift/ImageVIew.swift
  Homework/Sunwoong/Homework/ObserverPatternInSwift/ObserverPatternInSwift/MainViewController.swift
  Homework/Sunwoong/Homework/ObserverPatternInSwift/ObserverPatternInSwift/SceneDelegate.swift
  Homework/Sunwoong/Homework/ObserverPatternInSwift/ObserverPatternInSwift/SliderView.swift
  Homework/Sunwoong/Homework/ObserverPatternInSwift/ObserverPatternInSwift/Subject.swift
  Homework/Sunwoong/Homework/ObserverPatternInSwift/ObserverPatternInSwift/Subjectable.swift
  Homework/Sunwoong/Homework/ObserverPatternInSwift/ObserverPatternInSwift/TextfieldView.swift
Labels: question

#41 Create 3주차 homework
  Homework/Sunwoong/Homework/3주차 homework
Labels: need merge

#38 3주차 과제 - Stream의 구현체의 사용처를 각 구현체별로 생각 해보기
  Homework/Kyusik/Homework2/3주차 과제 - Stream의 구현체의 사용처를 각 구현체별로 생각 해 보기.md
Labels: need merge

#42 3주차 과제
  Homework/Handnew04/.DS_Store
  Homework/Handnew04/Homework/3주차과제.md
Labels: need merge

#43 3주차 과제 - Stream의 구현체의 사용처를 각 구현체별로 생각 해보기
  Homework/LeeChungWoo/RxStudy/app/src/main/java/com/lcw/study/rxstudy/step3/stream.md
Labels: need merge

#40 3주차과제-Stream 구현체 사용처 추측하기.
  Homework/Taewoo/Homework/3주차-Stream 구현체 사용처 추측하기..md
Labels: need merge, Homework

#47 4주차 과제 - Just 함수 구독해보기
  Homework/LeeChungWoo/RxStudy/app/build.gradle
  Homework/LeeChungWoo/RxStudy/app/src/main/java/com/lcw/study/rxstudy/step4/SubscribeJust.kt
Labels: Homework
